spring:
  application:
    name: learner-product-api
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    password: Sk@ndh15
    url: jdbc:mysql://localhost:3306/product_managment?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8132
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    password: Sk@ndh15
    url: jdbc:mysql://localhost:3306/product_managment?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://34.125.14.97:32770/eureka/